dependencies:
- base >= 4.7 && < 5
- postgresql-simple

library:
  source-dirs: src

executables:
  hello-world-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello-world-app

tests:
  hello-world-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello-world-app
